apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test2
  name: test2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test2
    spec:
      containers:
      - image: gridacr1246213.azurecr.io/grid-capstone:edf4ac1d6bf88f2a6fb0cefb79774fe06bf24764
        name: hello-world
        resources: {}
      imagePullSecrets:
      - name: tokensecret
status: {}